# Generated by Django 4.0.3 on 2022-03-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticket_options_commentticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
