# Generated by Django 4.0.3 on 2022-03-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentTicket_Ticket', to='support.commentticket'),
        ),
    ]
