# Generated by Django 4.0.3 on 2022-04-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_commentticket_parent_alter_commentticket_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentticket',
            name='moder',
        ),
    ]
